### ISSUE TITLE
[bug] Error: Unexpected token

### ISSUE THREAD

**Issue by onepiecehung** [sinkaroid/jandapress#14]
**Describe the bug**
When I try running this, I got the error like this image

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Node version [18.12.1]
 - Typescript version [4.9]

![image](https://user-images.githubusercontent.com/24888125/210200652-2f4b75cf-505a-404e-8ccc-81a6ee32aace.png)

**Comment by sinkaroid** [comment]
Is that logs from nhentai with cloudflare failed response or what? If yes that mean their internal IP was changed, this [Internal IP](https://github.com/sinkaroid/jandapress/blob/master/src/utils/options.ts#L10) still working for me, tested here https://sinkaroid.github.io/jandapress/#api-nhentai-Random_nhentai

**Comment by onepiecehung** [comment]
I don't know exactly what logs which from when I try to build and run this, use Axios for calling API I got this error, but today, it's working normally. thank you
