### ISSUE TITLE
Request support for 3hentai.net

### ISSUE THREAD

**Issue by bimbsms** [sinkaroid/jandapress#16]
Requesting support for 3hentai.net, it have some old manga that not available on other platform, the server also seems faster than NH. Thanks.

**Comment by sinkaroid** [comment]
3hentai has been added from this api but still not adding in Python SDK, example: https://janda.mod.land/3hentai/get?book=608979
with playground here: https://sinkaroid.github.io/jandapress/#api-3hentai

**Comment by sinkaroid** [comment]
Check the new release https://pypi.org/project/janda/ that was added
