### ISSUE TITLE
bug nhentai origin IP site not worked

### ISSUE THREAD

**Issue by zYxDevs** [sinkaroid/jandapress#22]
**Error**
When deploy on heroku used mirror nhentai site to get doujin. But the site maybe already down so didnt worked when get doujin.

There is another nhentai unofficial site, nhentai.to maybe can used for replacing old one.

**Comment by sinkaroid** [comment]
Check the new release that was fixed, whenever using IP make sure validate them with `npm run test`

**Comment by soujiokita** [comment]
There is no way for replacing the old/official nh, 
but it should possible make nhentai.to to the site support for jandapress, i can make this

**Comment by sinkaroid** [comment]
Iirc https://nhentai.to/ using kind of cache or its referer to protect images on their end (https://cdn.dogehls.xyz/) like #4, 
need prepare the reverse proxy first to implement for apis. I already has prototype on it, but PR are welcome or you can send me your stuff on my discord

**Comment by soujiokita** [comment]
Cannot arbitrary scrape then
