### ISSUE TITLE
Nhentai endpoint error

### ISSUE THREAD

**Issue by Hataken999** [sinkaroid/jandapress#29]
Bang IP dari nhentai udah mati bang, jadi endpoint nhentai udah gak bisa lagi.

**Comment by Offrise** [comment]
Sama pururin juga error bang

**Comment by zYxDevs** [comment]
well, patched again

**Comment by sinkaroid** [comment]
![Screenshot_41](https://github.com/sinkaroid/jandapress/assets/12372481/8caef5f2-67a9-4152-a466-e8b43146732d)
Observed 31juli msih pointing di ip yg sama, hari inipun masih. Kemungkinan portnya dibuat gak terbuka, cuma internal traffic yg bisa akses, jgn pakai ip origin sih, pake: [jandapress#nhentai-guide](https://github.com/sinkaroid/jandapress#nhentai-guide)

Buat pururin, ku cek ada yg ganti diwebnya, ntar diupdate

**Comment by sinkaroid** [comment]
@soujiokita could you bump your forks to 4ce195e pls?
