### ISSUE TITLE
bug: pururin (get book)

### ISSUE THREAD

**Issue by zYxDevs** [sinkaroid/jandapress#31]
**Describe the bug**
I recently found bugs on pururin api path, detailed on screenshoot.

![Screenshot_20230817-203339_Chrome](https://github.com/sinkaroid/jandapress/assets/45356875/9396134a-37f3-4ce4-bc94-c471f1d55644)

**Comment by sinkaroid** [comment]
Don't use mine use your own, janda.sinkaroid.org still on 3.8.1, I've assigned @soujiokita to bump his repo but apperently no? 🙃
